
/* This file was automatically generated by "generate_waveforms.py".
   (C) 2014 Christophe Jacquet.
   Released under the GNU GPL v3 license.
*/

#ifndef WAVEFORMS_H
#define WAVEFORMS_H

extern float waveform_biphase[576];

#endif /* WAVEFORMS_H */
